"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CODE = exports.ERROR_TYPE = void 0;
var ERROR_TYPE;
(function (ERROR_TYPE) {
    ERROR_TYPE[ERROR_TYPE["DATABASE_FAILURE_CONNECTION"] = 5000] = "DATABASE_FAILURE_CONNECTION";
    ERROR_TYPE[ERROR_TYPE["DATABASE_FAILURE_CREATION"] = 5001] = "DATABASE_FAILURE_CREATION";
    ERROR_TYPE[ERROR_TYPE["DATABASE_FAILURE_INTERN_PROCESS"] = 5002] = "DATABASE_FAILURE_INTERN_PROCESS";
})(ERROR_TYPE = exports.ERROR_TYPE || (exports.ERROR_TYPE = {}));
var CODE;
(function (CODE) {
    CODE["SUCESS"] = "SUCESS";
    CODE["FAILURE"] = "FAILURE";
    CODE["INTERN_ERROR"] = "INTERN_ERROR";
    CODE["ERROR"] = "ERROR";
})(CODE = exports.CODE || (exports.CODE = {}));
