
export enum ERROR_TYPE{
    DATABASE_FAILURE_CONNECTION = 5000,
    DATABASE_FAILURE_CREATION = 5001,
    DATABASE_FAILURE_INTERN_PROCESS = 5002,
}

export enum CODE{
    SUCESS = 'SUCESS',
    FAILURE = 'FAILURE',
    INTERN_ERROR = 'INTERN_ERROR',
    ERROR = 'ERROR'
}

